"""empty message

Revision ID: 0230fa95bd72
Revises: 2486876956f1
Create Date: 2016-12-25 13:02:21.359563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0230fa95bd72'
down_revision = '2486876956f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Genres', sa.Column('Genre_type', sa.String(length=20), nullable=True))
    op.drop_column('Genres', 'Genere_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Genres', sa.Column('Genere_type', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('Genres', 'Genre_type')
    # ### end Alembic commands ###
