"""empty message

Revision ID: 0f86bc50927b
Revises: 7b25bb77d376
Create Date: 2016-12-20 02:44:06.191197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f86bc50927b'
down_revision = '7b25bb77d376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('Books', sa.Column('Content_Id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Books', 'Content_Id')
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
