"""empty message

Revision ID: 2486876956f1
Revises: 3da7d86e8f12
Create Date: 2016-12-25 12:47:10.631687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2486876956f1'
down_revision = '3da7d86e8f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Count', sa.Column('genrescount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Count', 'genrescount')
    # ### end Alembic commands ###
