"""empty message

Revision ID: 3da7d86e8f12
Revises: 8e89fefd0a53
Create Date: 2016-12-25 12:29:36.891869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da7d86e8f12'
down_revision = '8e89fefd0a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Genre_id', sa.String(length=15), nullable=True),
    sa.Column('Genere_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Genre_id')
    )
    op.create_table('subscription',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['Genres.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('uid', 'gid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    op.drop_table('Genres')
    # ### end Alembic commands ###
