"""empty message

Revision ID: 63dc9967f823
Revises: b1d7512934d1
Create Date: 2016-12-21 00:05:16.101670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63dc9967f823'
down_revision = 'b1d7512934d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Count',
    sa.Column('userscount', sa.Integer(), nullable=False),
    sa.Column('bookscount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('userscount', 'bookscount')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Count')
    # ### end Alembic commands ###
