"""empty message

Revision ID: 8e89fefd0a53
Revises: eed3589664ec
Create Date: 2016-12-24 15:46:39.552032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e89fefd0a53'
down_revision = 'eed3589664ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Count', sa.Column('languagescount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Count', 'languagescount')
    # ### end Alembic commands ###
