"""empty message

Revision ID: b1d7512934d1
Revises: 2356d72716ca
Create Date: 2016-12-21 00:04:18.312250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d7512934d1'
down_revision = '2356d72716ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Count', sa.Column('bookscount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Count', 'bookscount')
    # ### end Alembic commands ###
