"""empty message

Revision ID: eed3589664ec
Revises: 63dc9967f823
Create Date: 2016-12-24 15:32:59.495410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eed3589664ec'
down_revision = '63dc9967f823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Language_id', sa.String(length=20), nullable=True),
    sa.Column('Name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Language_id')
    )
    op.create_table('preference',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('lid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lid'], ['Languages.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('uid', 'lid')
    )
    op.add_column(u'Users', sa.Column('Dob', sa.Date(), nullable=True))
    op.add_column(u'Users', sa.Column('Primary_language', sa.String(length=15), nullable=True))
    op.drop_column(u'Users', 'Languages')
    op.drop_column(u'Users', 'Age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'Users', sa.Column('Age', mysql.DATETIME(), nullable=True))
    op.add_column(u'Users', sa.Column('Languages', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column(u'Users', 'Primary_language')
    op.drop_column(u'Users', 'Dob')
    op.drop_table('preference')
    op.drop_table('Languages')
    # ### end Alembic commands ###
